services:
  db:
    image: postgres:18.1
    container_name: cuentas_claras_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cuentas_claras
    ports:
      - "5432:5432"
    volumes:
      - psql:/var/lib/postgresql

volumes:
  psql:
